// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZt4eQPqTwE6JoYqE3YyqW0IqE0xKxYqE',
    appId: '1:123456789:web:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'lifequestplatinum',
    authDomain: 'lifequestplatinum.firebaseapp.com',
    storageBucket: 'lifequestplatinum.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZt4eQPqTwE6JoYqE3YyqW0IqE0xKxYqE',
    appId: '1:123456789:android:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'lifequestplatinum',
    storageBucket: 'lifequestplatinum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZt4eQPqTwE6JoYqE3YyqW0IqE0xKxYqE',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'lifequestplatinum',
    storageBucket: 'lifequestplatinum.appspot.com',
    iosBundleId: 'com.lifequest.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZt4eQPqTwE6JoYqE3YyqW0IqE0xKxYqE',
    appId: '1:123456789:macos:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'lifequestplatinum',
    storageBucket: 'lifequestplatinum.appspot.com',
    iosBundleId: 'com.lifequest.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZt4eQPqTwE6JoYqE3YyqW0IqE0xKxYqE',
    appId: '1:123456789:windows:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'lifequestplatinum',
    authDomain: 'lifequestplatinum.firebaseapp.com',
    storageBucket: 'lifequestplatinum.appspot.com',
  );
}
